---
- name: HYPERV Stop-vm
  raw: powershell "Stop-vm -ComputerName {{ hyperv_computername }} -Name {{ export_box_as }}"
  ignore_errors: yes
  tags: deploy
  
- name: HYPERV Remove-VM export
  raw: powershell "Remove-VM -Verbose -ComputerName {{ hyperv_computername }} -Force -Name {{ export_box_as }}"
  ignore_errors: yes

- name: HYPERV Stop-vm import
  raw: powershell "Stop-vm -ComputerName {{ hyperv_computername }} -Name {{ import_box_as }}"
  ignore_errors: yes
  tags: del_import_vm
  
- name: HYPERV Remove-VM import
  raw: powershell "Remove-VM -Verbose -ComputerName {{ hyperv_computername }} -Force -Name {{ import_box_as }}"
  ignore_errors: yes
  tags: del_import_vm

- name: HYPERV Remove-Item
  raw: powershell "Remove-Item -Force -Recurse -Path '{{ hyperv_path }}'"
