---
- name: HYPERV Rename-VM
  raw: powershell "Rename-VM -ComputerName {{ hyperv_computername }} -Name {{ import_box_as }} -NewName {{ export_box_as }}"
  tags: rename_vm

- name: HYPERV Stop-vm
  raw: powershell "Stop-vm -ComputerName {{ hyperv_computername }} -Name {{ export_box_as }}"
  tags: stop_vm

- name: HYPERV Export-VM
  raw: powershell "Export-VM -Verbose -ComputerName {{ hyperv_computername }} -Name {{ export_box_as }} -Path '{{ export_path }}'"
  tags: export_vm

- name: HYPERV Optimize-VHD
  raw: powershell "Optimize-VHD -Verbose -ComputerName {{ hyperv_computername }} -Mode Full -Path '{{ export_path }}/{{ export_box_as }}/Virtual Hard Disks/{{ hyperv_file }}'"
  tags: optimize_vm
 
