---
- name:  HYPERV Get-ChildItem
  raw: powershell "Get-ChildItem -name -include '*.xml' -Path '{{ path }}'"
  register: out

- name: HYPERV Import-VM
  raw: powershell "Import-VM -Verbose -GenerateNewId -Copy -ComputerName {{ hyperv_computername }} -Path '{{ import_path }}' -VhdDestinationPath '{{ hyperv_path }}'"
  tags: import_vm

- name: HYPERV Start-vm
  raw: powershell "Start-vm -ComputerName {{ hyperv_computername }} -Name {{ import_box_as }}"
  tags: start_vm
  
- name: Pause for X seconds
  pause: seconds={{ delay }}
  tags: delay
