---
- name: Install required PHP modules
  sudo: yes
  apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
   - php5-gd
   - libssh2-php
  tags: install

- name: Create Wordpress database
  sudo: yes
  mysql_db: name={{ wp_name }} state=present

- name: Create Wordpress database user
  sudo: yes
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_name }}.*:ALL host='localhost' state=present
  
- name: Download wordpress.tar.gz
  sudo: yes
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest={{ wp_dir }}/wordpress-{{ wp_version }}.tar.gz
      
- name: Extract archive
  sudo: yes
  unarchive: src={{ wp_dir }}/wordpress-{{ wp_version }}.tar.gz dest={{ wp_dir }} copy=no

- name: Fetch random salts for Wordpress config
  sudo: no
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: wp_salt
  
- name: Copy Wordpress config file
  sudo: yes
  template: src=wp-config.php dest={{ wp_dir }}/{{ wp_name }}

- name: Change folder ownership
  sudo: yes
  file: path={{ wp_dir }}/{{ wp_name }} owner=www-data group=www-data state=directory recurse=yes

- name: Correct folder permissions
  sudo: yes
  command: "{{ item }}"
  with_items:
    - 'find {{ wp_dir }}/{{ wp_name }} -type f -exec chmod 664 {} +'
    - 'find {{ wp_dir }}/{{ wp_name }} -type d -exec chmod 775 {} +'
    - 'chmod 600 {{ wp_dir }}//{{ wp_name }}/wp-config.php'

- name: Restart services
  sudo: yes
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - nginx
    - php5-fpm
