---
- hosts: monitoring

  tasks:
    - name: Read config
      setup: filter=ansible_*
      register: ec2
    - name: Print config
      debug: var=ec2

  vars: 
    ansible_ssh_private_key_file: /Users/carles/.ssh/testing-env.pem