---
- hosts: localhost
  gather_facts: False
  connection: local
  
  roles:
    - { role: ec2, tags: ec2 }
    
  vars_files:
    - vars/aws-keys.yml
    
  vars:
    ansible_ssh_private_key_file: /Users/carles/.ssh/testing-env.pem
    ansible_ssh_user: ubuntu