---
- hosts: monitoring
  roles:
#    - { role: base, tags: base }
    - { role: ec2, tags: ec2 }
  vars: 
    ansible_ssh_private_key_file: /Users/carles/.ssh/testing-env.pem
    ansible_ssh_user: ubuntu