---
- hosts: all

  roles:
    - { role: base, tags: base }
    - { role: docker, tags: docker }
    - { role: ansible, tags: ansible }
    - { role: nagios, tags: nagios }
    - { role: elasticsearch, tags: elasticsearch }
    - { role: logstash, tags: logstash }
    - { role: kibana, tags: kibana }
    - { role: samba, tags: samba }
    - { role: jenkins, tags: jenkins }
    - { role: nginx, tags: nginx }
#    - { role: php, tags: php }
    - { role: bind, tags: bind }
    - { role: ssl-cert, tags: ssl-cert }
    - { role: logstash-forwarder, tags: logstash-forwarder }
    - { role: ec2, tags: ec2 }
