---
- hosts: all

  roles:
    - { role: base, tags: base }
    - { role: docker, tags: docker }
    - { role: ansible, tags: ansible }
    - { role: nagios, tags: nagios }
    - { role: elasticsearch, tags: elasticsearch }
    - { role: logstash, tags: logstash }
    - { role: kibana, tags: kibana }
    - { role: samba, tags: samba }
    - { role: jenkins, tags: jenkins }
    - { role: nginx, tags: nginx }
    - { role: bind, tags: bind }
    - { role: ssl-cert, tags: ssl-cert }


# commands...
# ansible-playbook install.yml -i hosts/all -l aws -t base,nagios
#
# review: --list-tasks --list-hosts -vvvv