---
- hosts: all

  roles:
    - { role: base, tags: base }
    - { role: docker, tags: docker }
    - { role: ansible, tags: ansible }
    - { role: nagios, tags: nagios }
    - { role: elasticsearch, tags: elasticsearch }
    - { role: logstash, tags: logstash }
    - { role: kibana, tags: kibana }
    - { role: samba, tags: samba }
    - { role: jenkins, tags: jenkins }
    - { role: nginx, tags: nginx }
    - { role: bind, tags: bind }
    - { role: ssl-cert, tags: ssl-cert }
    - { role: logstash-forwarder, tags: logstash-forwarder }


# commands...
# ansible-playbook install.yml -i hosts/all -l aws -u ubuntu -t base,kibana --private-key=/Users/carles/.ssh/elk.pem
# ansible-playbook install.yml -i hosts/aws -l aws-jenkins-ci -u ubuntu -t logstash-forwarder --private-key=/Users/carles/.ssh/jenkins-ci.pem
#
# review: --list-tasks --list-hosts -vvvv