---
- hosts: all

  roles:
    - { role: base, tags: base }
    - { role: docker, tags: docker }
    - { role: ansible, tags: ansible }
    - { role: nagios, tags: nagios }
    - { role: elasticsearch, tags: elasticsearch }
    - { role: logstash, tags: logstash }
    - { role: kibana, tags: kibana }
    - { role: samba, tags: samba }
    
#  vars:
#    vagrant_enable: True