---
# UNFINISHED & UNTESTED!
- name: apt-get install nagios_reqs @ vars
  sudo: yes
  apt: name={{ item }} state=latest  update_cache=yes cache_valid_time=3600
  with_items: nagios_reqs
  notify:
    - restart apache2
    - restart nagios3
