---
ansible_repo: 'ppa:ansible/ansible'
ansible_req_packages:
   - software-properties-common
   - python-pip
   - python-dev
   - build-essential
   - python-virtualenv
   - ansible
   - sshpass
   
pip_packages:
   - pywinrm
   - docker-py
   - boto
   - awscli
