---
wp_version: 4.3
wp_dir: /usr/share/nginx/html
wp_name: wordpress
wp_db_name: wordpress
wp_db_user: wordpress
wp_db_password: wordpress123
# WP: Debugging
wp_debug: False
# WP: Disable All Updates
auto_up_disable: false
# WP: Define Core Update Level
core_update_level: minor
# MariaDB settings
mysql_port: 3306
# Nginx settings
nginx_port: 80
server_hostname: wp.example.com