---
packages:
  - logstash-forwarder
package_name: logstash-forwarder
public_key_url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
repo_url: deb http://packages.elasticsearch.org/logstashforwarder/debian stable main

# folders
destination_cert: /etc/pki/tls/certs
origin_cert: /etc/pki/tls/certs/logstash-forwarder.crt
destination_conf: /etc

# templates
logstash_server: 192.168.32.10:5001
logstash_timeout: 15
files_to_log: '"paths": ["/var/log/syslog","/var/log/auth.log"],"fields": { "type": "syslog" }'
template_files: logstash-forwarder.conf