---
packages:
  - logstash-forwarder
package_name: logstash-forwarder
public_key_url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
repo_url: deb http://packages.elasticsearch.org/logstashforwarder/debian stable main

# folders
destination_cert: /etc/pki/tls/certs
origin_cert: /etc/pki/tls/certs/logstash-forwarder.crt
destination_conf: /etc

# templates
## ELK info...
log_server_ip: 192.168.32.10
server_port: 5001
logstash_timeout: 15
files_to_log: '"paths": ["/var/log/syslog","/var/log/auth.log"],"fields": { "type": "syslog" }'

# monitoring + ci servers...
# ci_to_log: '{"paths":["/var/log/jenkins/jenkins.log"],"fields":{"type":"jenkins"}},{"paths":["/var/log/nginx/*.log"],"fields":{"type":"nginx"}}'
# monitoring_to_log: '{"paths":["/var/log/nagios3/nagios.log"],"fields":{"type":"nagios"}},{"paths":["/var/log/apache2/*.log"],"fields":{"type":"apache2"}}'