---
- name: Install MariaDB
  sudo: yes
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
   - mariadb-server
   - python-mysqldb
   - python-mysql.connector
  tags: install

- name: MySQL configuration file
  sudo: yes
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf

#- name: MySQL local configuration file
#  sudo: yes
#  template: src=my.conf-user.j2 dest=./.my.cnf
    
- name: Start MariaDB Service
  sudo: yes
  service: name=mysql state=restarted enabled=yes