---
# echo 'mariadb-server-5.5 mysql-server/root_password password root' | debconf-set-selections
- name: debconf-set-selections mysql-server/root_password 
  sudo: yes
  debconf:
    name='mariadb-server-5.5'
    question='mysql-server/root_password'
    value='{{ maria_pass }}'
    vtype='password'

# echo 'mariadb-server-5.5 mysql-server/root_password_again password root' | debconf-set-selections
- name: debconf-set-selections mysql-server/root_password_again
  sudo: yes
  debconf:
    name='mariadb-server-5.5'
    question='mysql-server/root_password_again'
    value='{{ maria_pass }}'
    vtype='password'

# echo 'mariadb-server-5.5 mariadb-server/oneway_migration boolean true' | debconf-set-selections
- name: debconf-set-selections mariadb-server/oneway_migration
  sudo: yes
  debconf:
    name='mariadb-server-5.5'
    question='mariadb-server/oneway_migration'
    value='true'
    vtype='boolean'

- name: Install MariaDB
  sudo: yes
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
   - mariadb-server
   - python-mysqldb
   - python-mysql.connector
  tags: install

- name: MySQL configuration file
  sudo: yes
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf

- name: MySQL local configuration file
  template: src=my.conf-user.j2 dest=./.my.cnf
  when: user_folder_pass == True
    
- name: Start MariaDB Service
  sudo: yes
  service: name=mysql state=restarted enabled=yes