---
- name: add line to file 1
  sudo: yes
  lineinfile: dest=/etc/default/locale line='LC_ALL="en_GB.UTF-8"'

- name: add line to file 2
  sudo: yes
  lineinfile: dest=/etc/default/locale line='LANG="en_GB.UTF-8"'

- name: create /home/vagrant/.bash_profile
  command: touch /home/vagrant/.bash_profile
  when: vagrant_enable == True
  tags: vagrant

- name: add line to file 3
  lineinfile: dest=/home/vagrant/.bash_profile line='LC_ALL="en_GB.UTF-8"'
  when: vagrant_enable == True
  tags: vagrant

- name: add line to file 4
  lineinfile: dest=/home/vagrant/.bash_profile line='LANG="en_GB.UTF-8"'
  when: vagrant_enable == True
  tags: vagrant

- name: Language exports
  sudo: yes
  shell: '{{ item }}'
  with_items: exports

- name: Location commands
  sudo: yes
  command: '{{ item }}'
  with_items: location_commands
