---
- name: set timezone to UTC
  sudo: yes
  shell: echo "{{ ntp_timezone }}" | tee /etc/timezone

- name: reconfigure (Debian)
  sudo: yes
  shell: dpkg-reconfigure --frontend noninteractive tzdata

- name: Ensure NTP is at the latest version
  sudo: yes
  apt: name=ntp state=latest  update_cache=yes cache_valid_time=3600
  notify:
    - Restart NTP
    
- name: Ensure NTP is running and enabled at system start
  sudo: yes
  service: name={{ ntp_daemon }} state=started enabled=yes
  when: ntp_enabled

- name: Ensure NTP is stopped and disabled at system start
  sudo: yes
  service: name={{ ntp_daemon }} state=stopped enabled=no
  when: not ntp_enabled
  
- name: Add Spain daily cron job
  sudo: yes
  lineinfile: dest=/etc/cron.daily/ntpdate line='{{ cron_ntp }}' owner=root group=root mode=0755 create=yes
