---
- name: Install npm packages
  npm: name={{ item }} global=yes state=latest
  sudo: True
  with_items: npm_packages
  
- name: Install testing packages
  npm: name={{ item }} global=yes state=latest
  sudo: True
  with_items: testing_packages
  
#- name: Install headless packages for Debian
#  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=latest
#  sudo: True
#  with_items: apt_packages
#  when: ansible_os_family == "Debian"
  
- name: whereis phantomjs
  command: whereis phantomjs
  register: phantomjs_path

- debug: var=phantomjs_path.stdout

