---
node_packages:
  - build-essential
  - nodejs
#  - firefox
#  - xvfb
#  - chromium-chromedriver
#  - chromium-browser

npm_packages:
  - phantomjs

install_nodejs_macosx: scripts/install-nodejs-macosx.sh

install_nodejs_debian: scripts/install-nodejs-debian.sh
install_nodejs_debian_command: curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
