---
- name: Instalar clave pública
  sudo: yes
  apt_key: url={{ public_key_url }} state=present
      
- name: Añadir URL de repositorio
  sudo: yes
  apt_repository: repo='{{ repo_url }}' state=present update_cache=yes

- name: Instalar ROLE
  sudo: yes
  apt: name={{ item }} state=latest  update_cache=yes cache_valid_time=3600
  with_items: packages

- name: Restrict outside access to ROLE (only localhost allowed)
  sudo: yes
  lineinfile: dest={{ config_file }} line='{{ config_line }}'
#  notify: Reiniciar servicio ROLE
  when: localhost_only == True

- name: Reiniciar servicio ROLE
  sudo: yes
  service: name='{{ package_name }}' state=restarted enabled=yes
