---
- name: LAUNCH assign_public_ip ON
  ec2:
    aws_access_key: '{{ ec2_access_key }}'
    aws_secret_key: '{{ ec2_secret_key }}'
    key_name: '{{ ec2_key_name }}'
    instance_type: '{{ ec2_instance_type }}'
    image: '{{ ec2_image }}'
    region: '{{ ec2_region }}'
    wait: '{{ ec2_wait }}'
    assign_public_ip: '{{ ec2_assign_public_ip }}'
    vpc_subnet_id: '{{ ec2_vpc_subnet_id }}'
    group: '{{ ec2_group }}'
    count: '{{ ec2_count }}'
    count_tag:
      Name: '{{ ec2_count_tag_name }}'
    instance_tags:
      Name: '{{ ec2_instance_tags_name }}'
      Type: '{{ ec2_instance_tags_type }}'
  register: ec2
  tags: C

- name: ADD new instance to host group
  add_host: hostname={{ item.public_ip }} groupname={{ ec2_groupname }}
  with_items: ec2.instances
  tags: C

- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=15 timeout=60 state=started
  with_items: ec2.instances
  tags: C
# TODO: still thinking...
- name: ADD instance_id to list roles/ec2/vars/main.yml
  lineinfile: dest=roles/ec2/vars/main.yml line='  - {{ item.id }}' state=present
  with_items: ec2.instances
  tags: C
# TODO: still thinking...
- name: ADD IP to list hosts/ec2-aws
  lineinfile: dest=hosts/ec2-aws insertafter='^\[monitoring\]' line='{{ item.public_ip }}' state=present
  with_items: ec2.instances
  tags: C

#- debug: var={{ item }}
#  with_items: ec2.instances
#  tags: C
