---
selenium_stack:
  - firefox
  - xvfb
  - chromium-chromedriver
  - chromium-browser

selenium_server_standalone: http://goo.gl/PJUZfa
selenium_jar: selenium-server-standalone-2.48.2.jar

selenium_folder: /usr/lib/selenium
selenium_logs: /var/log/selenium

selenium_node: node -hub http://10.10.10.1:4444/grid/register/
selenium_hub: hub

crontab_job: "@reboot sh -c 'Xvfb :99 -ac -screen 0 1024x768x8 > /tmp/xvfb.log 2>&1 &'"