---
cert_name: default-certificate-name

# folders
cert_folder: /etc/pki/tls
keyout_folder: private
out_folder: certs
certs_folders:
  - "{{ cert_folder }}/{{ keyout_folder }}"
  - "{{ cert_folder }}/{{ out_folder }}"
  
# templates
source_conf: openssl.cnf
destination_conf: /etc/ssl/openssl.cnf
log_server_ip: 192.168.32.10
# vagrant environments: ansible_eth1.ipv4.address