---
base_packages:
   - git
   - curl
   - vim
   - screen
   - ssh
   - tree
   - lynx
   - links
   - links2
   - build-essential
   - make
   - automake
   - zip
   - byobu
   - htop
   - rsync
   - default-jdk
   - sqlite3
   - ntp  
   - sysstat
   - dstat
   - screen
   - telnet
   - traceroute
   - mtr
   - lsof
   - fail2ban
   - wget