---
vagrant_enable: False

apache_packages:
  - apache2
  - php5
  - libapache2-mod-php5
  - php5-mcrypt
  - php5-cli
  - php5-mysql
  - php5-gd

apache_modules:
  - rewrite
  - alias
  - ssl

install_composer:
  - 'curl -sS https://getcomposer.org/installer | php'
  - 'mv composer.phar /usr/local/bin/composer'

upload_filesize: 64M