---
- name: Create Selenium folders
  sudo: yes
  file: path="{{ item }}" state=directory mode=0755
  with_items:
    - "{{ selenium_folder }}"
    - "{{ selenium_logs }}"

- name: Download Selenium jar
  sudo: yes
  get_url: url={{ selenium_server_standalone }} dest=/usr/lib/selenium/
  tags:
    - download

- name: Pass hub variable to config
  set_fact:
    selenium_config: "{{ selenium_hub }}"

- name: Copy node init.d template
  sudo: yes
  template: src=selenium_init.sh dest=/etc/init.d/selenium owner=root group=root mode=0755

- name: Start Selenium service
  sudo: yes
  service: name=selenium state=started enabled=yes