---
user_to_docker:
  - vagrant
  - ubuntu

docker_packages:
  - bridge-utils
  - apt-transport-https
  - ca-certificates
  - apparmor
  - python-pip
  - python-virtualenv

keyserver: 'hkp://p80.pool.sks-keyservers.net:80'
keyserver_id: 58118E89F3A912897C070ADBF76221572C52609D
docker_sources: 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'