- name: ensure ntp is at the latest version
  sudo: yes
  sudo_user: root
  apt: pkg=ntp state=latest
  notify:
    - restart ntp

- name: aptget update if needed
  sudo: yes
  sudo_user: root
  apt: update_cache=yes

- name: aptget upgrade if needed
  sudo: yes
  sudo_user: root
  apt: upgrade=safe

- name: Check if anything needs autoremoving
  sudo: yes
  sudo_user: root
  shell: apt-get -y --dry-run autoremove | grep -q "0 to remove"
  register: check_autoremove
  ignore_errors: True
  changed_when: False
  always_run: True

- debug: var=check_autoremove

- name: Autoremove unused packages
  sudo: yes
  sudo_user: root
  command: apt-get -y autoremove
  when: "check_autoremove.rc != 0"
  register: autoremove_output

- debug: var=autoremove_output

- name: apt-get install base_packages
  sudo: yes
  sudo_user: root
  apt: package={{ item }} state=latest
  with_items: base_packages
  ignore_errors: yes

- name: add line to file 1
  sudo: yes
  sudo_user: root
  lineinfile: dest=/etc/default/locale line='LC_ALL="en_GB.UTF-8"'

- name: add line to file 2
  sudo: yes
  sudo_user: root
  lineinfile: dest=/etc/default/locale line='LANG="en_GB.UTF-8"'

- name: create /home/vagrant/.bash_profile
  command: touch /home/vagrant/.bash_profile

- name: add line to file 3
  lineinfile: dest=/home/vagrant/.bash_profile line='LC_ALL="en_GB.UTF-8"'

- name: add line to file 4
  lineinfile: dest=/home/vagrant/.bash_profile line='LANG="en_GB.UTF-8"'
