---
- name: aptget upgrade if needed
  sudo: yes
  apt: upgrade=safe update_cache=yes cache_valid_time=3600

- name: Check if anything needs autoremoving
  sudo: yes
  shell: apt-get -y --dry-run autoremove | grep -q "0 to remove"
  register: check_autoremove
  ignore_errors: True
  changed_when: False
  always_run: True

- debug: var=check_autoremove

- name: Autoremove unused packages
  sudo: yes
  command: apt-get -y autoremove
  when: "check_autoremove.rc != 0"
  register: autoremove_output

- debug: var=autoremove_output

- name: apt-get install base_packages
  sudo: yes
  apt: name={{ item }} state=latest  update_cache=yes cache_valid_time=3600
  with_items: base_packages
  ignore_errors: yes
  