---
- name: Instalar clave pública
  sudo: yes
  apt_key: url={{ public_key_url }} state=present
      
- name: Añadir URL de repositorio
  sudo: yes
  apt_repository: repo='{{ repo_url }}' state=present update_cache=yes
  
- name: Instalar ROLE
  sudo: yes
  apt: name={{ item }} state=latest  update_cache=yes cache_valid_time=3600
  with_items: packages
  
- name: Copiar templates a etc de ROLE
  sudo: yes
  template: src={{ item }} dest={{ template_folder }} owner=root group=root mode=0644
  with_items: template_files

- name: Reiniciar servicio ROLE
  sudo: yes
  service: name='{{ package_name }}' state=restarted enabled=yes

- name: Copiar certificado creado por ROLE ssl-cert
  fetch: src={{ logstash_ssl_certificate }} dest=roles/logstash-forwarder/files/logstash-forwarder.crt flat=yes fail_on_missing=yes
  register: exists_cert
